env:
  browser: true
  es2021: true
  node: true
extends: "airbnb-base"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    no-console: "off",
    import/extensions: "off",
    quotes: ["error", "single"],
    comma-dangle: ["error", "never"],
    operator-linebreak: ["error", "none"],
  }
